version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4020:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
  frontend:
    build: .
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    restart: always
    environment:
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-<set-your-hosts-here>}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:4020}
      - VITE_CATEGORY_NAMES=${VITE_CATEGORY_NAMES:- Starters,Salads,Drinks}
      - VITE_CATEGORY_PER_QTY=${VITE_CATEGORY_PER_QTY:-5,5,4}
      - VITE_MAX_QTY=${VITE_MAX_QTY:-6,2,4}
