version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4020:8000"
    volumes:
      - ./backend:/app
    restart: always
  frontend:
    build: .
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    restart: always
